### ISSUE TITLE
The results on QNRF cannot be reproduced.

### ISSUE THREAD

**Issue by guoxiangyv** [ZPDu/Domain-general-Crowd-Counting-in-Unseen-Scenarios#4]
The results on partB (mae: 12.524479142973703 mse: 24.58619457069881) can be successfully reproduced using the provided SHA model, but the results on QNRF(mae: 198.86608207803144 mse: 391.064940641501) cannot be reproduced.

**Comment by ZPDu** [comment]
Hi, thanks for pointing out the problem. I think the reason is we modified the pre-processing code of QNRF in C-3 Framework because it sets the maxSize=1024, while in our work we follow a common practice by setting it to 1920. I will also upload our processed QNRF dataset later.

**Comment by guoxiangyv** [comment]
Thank you very much for your answers and look forward to processing the dataset.
