### ISSUE TITLE
About the cluster visualization

### ISSUE THREAD

**Issue by qycurious** [ZPDu/Domain-general-Crowd-Counting-in-Unseen-Scenarios#6]
Can you please provide the code for t-SNE visualisation of re-encoded features? thank you very much！！

**Comment by ZPDu** [comment]
Hi, as I don't have access to the code on the previous server, I would recommend using [openTSNE](https://github.com/pavlin-policar/openTSNE) to write your script. You just need the re-encoded features from the DI memory and all DS memories for the analysis. Then, you could plot the figure based on the returned coordinates from TSNE.

**Comment by qycurious** [comment]
OK, thank you!
