### ISSUE TITLE
Question about 'msMeta'

### ISSUE THREAD

**Issue by D-VVY** [ZPDu/Domain-general-Crowd-Counting-in-Unseen-Scenarios#8]
Hello, author. Thank you for your excellent work! I have a question I hope you can answer. In the default parameters of your model, you wrote 'msMeta'.

![image](https://github.com/user-attachments/assets/623dbb23-a98c-42af-a2e6-75bf7b9beb78)

However, this option is not available in your module creation file, so I get an error when running the program locally. Is there something I might have missed? I look forward to your reply. Thank you.

![image](https://github.com/user-attachments/assets/8a712240-8d86-473e-841f-c415f77ba444)

**Comment by ZPDu** [comment]
Hi, thanks for your interest. For this issue, changing it to 'memMeta' would work.
