### ISSUE TITLE
产生的一些警告

### ISSUE THREAD

**Issue by Li-Xiuxiu** [ZPDu/Domain-general-Crowd-Counting-in-Unseen-Scenarios#9]
运行代码时有一个警告如下：
/home/user914/anaconda3/envs/chenlang/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
![image](https://github.com/user-attachments/assets/2aa0920c-19c1-41ec-bee3-b918681bc7aa)
查询说需要把
kmeans = KMeans(n_clusters=n_clusters)
改为
kmeans = KMeans(n_clusters=n_clusters, n_init=n_init)，才能消除
但是我不知道应该把n_init设置为多少？请问您遇到过这个警告吗？

**Comment by Li-Xiuxiu** [comment]
还有一个关于数据加载器的警告
/home/user914/anaconda3/envs/chenlang/lib/python3.8/site-packages/torch/utils/data/dataloader.py:487: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 16, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
(300, 512)
无论我如何更改
![image](https://github.com/user-attachments/assets/b4ec1979-d52c-4da9-8b13-bbae51a62b2f)
中的default值都无法改变，请问如何消除这个警告？

**Comment by ZPDu** [comment]
您好，第一个警告应该是function版本更新后的问题，我之前应该没有遇到过，您也可以尝试一下按warning指示改为auto，观察一下结果影响会不会很大。另一个数据加载器警告看起来更像是您系统特有的警告，可以尝试找到dataloader的具体位置修改num_workers试一试
